version: "3.9"
services:
  db:
    image: postgres:15
    container_name: core_pg
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: core
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../sql:/docker-entrypoint-initdb.d
  redis:
    image: redis:7
    container_name: core_redis
    ports:
      - "6379:6379"
volumes:
  pgdata:
